openapi: 3.0.0
info:
  title: Sample API with Standard Fields
  version: 1.0.0
paths:
  /api/v2/platform/environments:
    get:
      summary: Get all environments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Environment'
                  meta:
                    type: object
                    properties:
                      pagination:
                        $ref: '#/components/schemas/PaginationMeta'
                required:
                  - data
    post:
      summary: Create a new environment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Environment'
                required:
                  - data
  /api/v2/platform/environments/{id}:
    get:
      summary: Get environment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Environment'
                required:
                  - data
components:
  schemas:
    PaginationMeta:
      type: object
      properties:
        count:
          type: integer
        pageNumber:
          type: integer
        pageSize:
          type: integer
        nextPage:
          type: integer
          nullable: true
        totalPages:
          type: integer
    EnvironmentInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        environmentType:
          type: string
          enum: [development, staging, production]
      required:
        - name
        - environmentType
    Environment:
      type: object
      properties:
        id:
          type: string
          description: The opaque ID of the environment
        type:
          type: string
          description: The type of object being returned
          example: "environment"
        name:
          type: string
        description:
          type: string
        environmentType:
          type: string
          enum: [development, staging, production]
        createdBy:
          type: string
        createdTime:
          type: string
          format: date-time
        updatedBy:
          type: string
        updatedTime:
          type: string
          format: date-time
      required:
        - id
        - type
        - name
        - environmentType
        - createdBy
        - createdTime
        - updatedBy
        - updatedTime
